import { MetadataRoute } from 'next'

export default function robots(): MetadataRoute.Robots {
  const baseUrl = 'https://mydiscordbot.com'

  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/fr/',
          '/en/',
          '/fr/command',
          '/en/command',
          '/fr/bots',
          '/en/bots',
          '/fr/bots/*',
          '/en/bots/*',
          '/fr/privacy-policy',
          '/en/privacy-policy',
          '/fr/faq',
          '/en/faq',
          '/fr/command_finish',
          '/en/command_finish',
        ],
        disallow: [
          '/api/',
          '/admin/',
          '/_next/',
          '/private/',
          '*.json',
          '/fr/command_finish/',
          '/en/command_finish/',
        ],
        crawlDelay: 1,
      },
      {
        userAgent: 'Googlebot',
        allow: [
          '/',
          '/fr/',
          '/en/',
          '/fr/command',
          '/en/command',
          '/fr/bots',
          '/en/bots',
          '/fr/bots/*',
          '/en/bots/*',
          '/fr/privacy-policy',
          '/en/privacy-policy',
          '/fr/faq',
          '/en/faq',
        ],
        disallow: [
          '/api/',
          '/admin/',
          '/_next/',
          '/private/',
          '*.json',
          '/fr/command_finish/',
          '/en/command_finish/',
        ],
        crawlDelay: 0,
      },
      {
        userAgent: 'Bingbot',
        allow: [
          '/',
          '/fr/',
          '/en/',
          '/fr/command',
          '/en/command',
          '/fr/bots',
          '/en/bots',
          '/fr/bots/*',
          '/en/bots/*',
          '/fr/privacy-policy',
          '/en/privacy-policy',
          '/fr/faq',
          '/en/faq',
        ],
        disallow: [
          '/api/',
          '/admin/',
          '/_next/',
          '/private/',
          '*.json',
          '/fr/command_finish/',
          '/en/command_finish/',
        ],
        crawlDelay: 1,
      },
    ],
    sitemap: `${baseUrl}/sitemap.xml`,
    host: baseUrl,
  }
}
