name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker buildx build --push \
            --tag ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_APP }}:latest .

      # Configuration de la clé SSH
      # - name: Install SSH key
      #   uses: shimataro/ssh-key-action@v2
      #   with:
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     known_hosts: unnecessary
      #     if_key_exists: replace

      # # Connexion SSH au serveur physique (Proxmox)
      # - name: Connect to physical server
      #   uses: appleboy/ssh-action@v0.1.10
      #   with:
      #     host: ${{ secrets.PROXMOX_HOST }}
      #     username: ${{ secrets.PROXMOX_USERNAME }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     port: 22
      #     debug: true
      #     command_timeout: 20m
      #     script: |
      #       echo "Connecting to VM..."
      #       ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} '
      #         echo "Connected to VM"
      #         echo "Current directory: $(pwd)"
      #         if [ -f docker-compose.yml ]; then
      #           echo "docker-compose.yml found"
      #           sudo docker-compose pull
      #           sudo docker-compose down
      #           sudo docker-compose up -d --remove-orphans
      #         else
      #           echo "Error: docker-compose.yml not found"
      #           exit 1
      #         fi
      #       ' 